name: flutter_application_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  flutter_screenutil: ^5.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/svg/background_1.svg
    - assets/svg/background_2.svg
    - assets/png/background1.png